### ISSUE TITLE
Change consteval to constexpr

### ISSUE THREAD

**Issue by tgurriet** [boost-ext/reflect#15]
Hello.

Thanks for the great library!

Is it possible to change `consteval` to `constexpr` for `type_name` and `member_name`?

This prevents constructs like.
```
A val;

static constexpr size_t SIZE = reflect::size<A>;

static_for<SIZE>(
  [&](const auto i)
  {
    std::cout << std::string_view(reflect::member_name<i.value>(val)) << std::endl;
    std::cout << std::string_view(reflect::type_name(reflect::get<i.value>(val)))
              << std::endl;
  });
```
Where `static_for` is a recursive call wrapper.

**Comment by krzysztof-jusiak** [comment]
Fixed by https://github.com/boost-ext/reflect/commit/9e4354442ce72b7730b3adb483e41ce1976e24eb
