### ISSUE TITLE
results compiling below code with -ftime-trace 

### ISSUE THREAD

**Issue by arturbac** [boost-ext/reflect#35]
Continuing from our reddit discussion, I am attaching promised results 
This is test code the same for both
![obraz](https://github.com/boost-ext/reflect/assets/14975842/66dbf24e-8980-4a8a-8dd4-69b6ce3dcb3f)

![obraz](https://github.com/boost-ext/reflect/assets/14975842/b68f3dd7-8e16-4c5f-90ea-e535518c5d2a)

[magic_enum_reflect_ut.cc.json](https://github.com/boost-ext/reflect/files/14445678/magic_enum_reflect_ut.cc.json)
[reflect_enum_reflect_ut.cc.json](https://github.com/boost-ext/reflect/files/14445679/reflect_enum_reflect_ut.cc.json)
![Screenshot_20240228_220426](https://github.com/boost-ext/reflect/assets/14975842/09c10f2a-816d-4d04-89b1-d2f9902870d7)

**Comment by arturbac** [comment]
You have 8 EvaluateAsRValue with lower and higher times
example 100ms wasted for unit test
EvaluateAsRValue reflect-src/reflect:337:19, col:76 96,178 ms
static_assert(std::string_view{"_42"} == enum_name<42, 256>(sparse::_42));

**Comment by krzysztof-jusiak** [comment]
Thanks. Fixed. Please compare v1.0.8+. The following are the results for v1.0.8 with static_assert enabled.

```
time g++ -std=c++20 magic_enum.cpp # 0.322ms
time g++ -std=c++20 reflect.cpp # 0.318ms // with tests
``` 

Tested code

magic_enum:HEAD
```
#include <magic_enum/magic_enum_all.hpp>

enum E { _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16 };

int main() {
  (void)magic_enum::enum_name(E::_1);
  (void)magic_enum::enum_name(E::_2);
  (void)magic_enum::enum_name(E::_3);
  (void)magic_enum::enum_name(E::_4);
  (void)magic_enum::enum_name(E::_5);
  (void)magic_enum::enum_name(E::_6);
  (void)magic_enum::enum_name(E::_7);
  (void)magic_enum::enum_name(E::_8);
  (void)magic_enum::enum_name(E::_9);
  (void)magic_enum::enum_name(E::_10);
  (void)magic_enum::enum_name(E::_11);
  (void)magic_enum::enum_name(E::_12);
  (void)magic_enum::enum_name(E::_13);
  (void)magic_enum::enum_name(E::_14);
  (void)magic_enum::enum_name(E::_15);
  (void)magic_enum::enum_name(E::_16);
}
```

reflect:HEAD (v1.0.8)

```
#include <refelct>

enum E { _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16 };

int main() {
  (void)magic_enum::enum_name(E::_1);
  (void)magic_enum::enum_name(E::_2);
  (void)magic_enum::enum_name(E::_3);
  (void)magic_enum::enum_name(E::_4);
  (void)magic_enum::enum_name(E::_5);
  (void)magic_enum::enum_name(E::_6);
  (void)magic_enum::enum_name(E::_7);
  (void)magic_enum::enum_name(E::_8);
  (void)magic_enum::enum_name(E::_9);
  (void)magic_enum::enum_name(E::_10);
  (void)magic_enum::enum_name(E::_11);
  (void)magic_enum::enum_name(E::_12);
  (void)magic_enum::enum_name(E::_13);
  (void)magic_enum::enum_name(E::_14);
  (void)magic_enum::enum_name(E::_15);
  (void)magic_enum::enum_name(E::_16);
}
```

**Comment by arturbac** [comment]
??
Wall Duration	22,783 ms
"reflect::v1_0_8::(anonymous class)::operator()<reflect::v1_0_8::(lambda at /home/artur/projects/amrpc/targeo_amrpc/build/clang-release-time-trace-auto/_deps/reflect-src/reflect:569:33){}>"
static_assert(([]<auto expect = [](const bool cond) { return std::array{true}[not cond]; }> {

Wall Duration	68,613 ms
"reflect::v1_0_8::(anonymous class)::operator()<reflect::v1_0_8::(lambda at /home/artur/projects/amrpc/targeo_amrpc/build/clang-release-time-trace-auto/_deps/reflect-src/reflect:659:33){}>"

static_assert(([]<auto expect = [](const bool cond) { return std::array{true}[not cond]; }> {

Wall Duration 67,197 ms
"reflect::v1_0_8::(anonymous class)::operator()<reflect::v1_0_8::(lambda at /home/artur/projects/amrpc/targeo_amrpc/build/clang-release-time-trace-auto/_deps/reflect-src/reflect:746:33){}>"

static_assert(([]<auto expect = [](const bool cond) { return std::array{true}[not cond]; }> {

**Comment by krzysztof-jusiak** [comment]
Can you elaborate, pleas. I don't follow this numbers as they are out of context. Is there any project/benchmark I can try or are there any steps I can follow to reproduce it, what setup is used, compiler, how many TUs? I don't see any issues from v1.0.8 with compilations times on benchmarks I'm performing, if anything, it seems faster than other projects, so would appreciate some guidance here so that I can track down what's happening.

**Comment by arturbac** [comment]
Will continue later after work, can not right now.

**Comment by krzysztof-jusiak** [comment]
no worries, thanks :+1:

**Comment by arturbac** [comment]
1) example for reflect in this comments You wrote is invalid (magic_enum:: namespace)
2) reflect doesn't work with clang and enums with undefined underlying type
![obraz](https://github.com/boost-ext/reflect/assets/14975842/c5da17b1-10c2-4486-9770-11e3c5cb3f8f)
3) Here You have comparison for reflect with unit tests on top compared to reflect with disabled unit tests for the example You provided in this topic
![main_cc](https://github.com/boost-ext/reflect/assets/14975842/fbe1027e-55aa-4090-a4ef-7903107384f2)
And now explanation:
For me it doesn't matter how it compares to magic_enum as magic_enum at production I can use only with a rule single enum_name wrapper in single translation unit per enum. When i tried when i started using it use  it as constexpr scattering magic_enum::enum_name across project with ~1mln lines of code, it was disaster compiler was spending almost half of total time of building entire solution on compiling enum name from magic_enum.
So now I am very cautious to compile time meta and check it carefully.
For me it is a snow ball effect when in many files given include is included in project and used, unit tests of external project are simply not allowed at every solution compilation as it is pure waste of time, I don not unit test spdllog, ut, libc++ and many more at compile time, I can't ;-)
I have ready pull request and will do it it is up to You what You are going to do with it.
Btw **amazing!** work You did with ut and reflect.
Pozdro.

**Comment by krzysztof-jusiak** [comment]
Okay, thanks for the update, the details and traces. I understand the scale of the project and your requirements. I think it's fair to have option to disable the static tests overall. The only part important for my is that by default the tests will be enabled but can be opt out. Going to merge #37 but will refactor it slightly as a follow-up to avoid #ifdefs all over the place. Thanks.

**Comment by arturbac** [comment]
Just to let You know
reflect:enum_name is 10x faster now in Function Instantiation than magic_enum, excellent work with reflect!
When I measured it with time-trace it is on my HW
magic_enum : 69,7ms
feflect : 6,9 ms
![obraz](https://github.com/boost-ext/reflect/assets/14975842/677d00d6-462b-4787-81ca-fb01ebebafcc)

**Comment by krzysztof-jusiak** [comment]
Pretty cool, thanks for sharing. Just out of curiosity, it seems like you are compiling quite a big project with a lot translation units, hence was wondering whether you are using precompiled headers for third-party library or that not possible for some reason?

**Comment by arturbac** [comment]
I am working on few projects in company so situation is complicated :-) 
The better granulation of source code  for multiple cores (many libraries and translation units)  the less efficient pch is as You have bottle neck for pch creation at every library. So one of projects that is mostly my baby very well layered into multiple libraries with relatively small translation units, with high quality include hygiene is very fast for compiling on multiple cores but it doesn't like heavy includes, and using pch on it causes actually slower compile times that without pch. And I was hit not by inclusion times with magic_enum but with instantiation as you see 80ms per every enum_name in given enum type in given translation unit is a rather heavy influence on total time when used all across project and pch will not solve instantiation.
Second project result of work of multiple ppl has terrible translation units with even 30-50k lines of code and it is using pch.
I personally don't use pch in debug mode with IDE as it is  affecting proper header hygiene during development.

**Comment by arturbac** [comment]
Just to validate results,  I looked at Your code and I am not sure if comparison is fair, as You cut names at runtime so reflect and magic enum have different outcome, ME generates enum literals while reflect generates functions names and runtime code so this is not very comparable by looking only just at Instantiation time.

**Comment by krzysztof-jusiak** [comment]
Fixed now by https://github.com/boost-ext/reflect/commit/0f80f4fa447e478d6f96d37830cadcfb6a590bc6.
Expecting a bit slower compilation times as more things are done at run-time but not by much.

**Comment by arturbac** [comment]
In real world case using enum_name without enum bounds[ it doesn't compile with clang](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM1ykrgAyeAyYAHI%2BAEaYxCAArAmkAA6oCoRODB7evv6BaRmOAqHhUSyx8Um2mPbFDEIETMQEOT5%2BATV1WY3NBKWRMXGJyQpNLW15nWN9A%2BWVIwCUtqhexMjsHOYAzGHI3lgA1Cbbbk5jxJisJ9gmGgCCO3sHmMenCqvrmAD6tKii9Rud0eZl2DH2XiOJzcXkctEIAE8gQ8nuCXm83BcwsBvgA3PCYADuyJBYIhUNOzWITCR21uKJRoLwVEODFQBEOWBo4XQEAAStgAGLBbBuAAq32wETkAFlvjKAJIRRbAnZcsKvAXC0USqWy%2BVKw4aVWg1zM1WM3Ystkc9U8/lCkXiyXSuUy%2B4ADRVlrtmsdOpd%2BvdHsOADZJCbtmaqBb7hcvA5DoctU6JUIxXy5OLjgB2CyHXGoPDoABUhxl2BlFmwfJO%2BcYPkO%2ByYCgUhz1Mtz%2BYAavdgnJsLmACJ14ejgD048OCBbhyIh1ihzCc4Qr2Af2iYlZrEwChSTA2seYbD3B9eWCadC7wIImBYKQMt%2BhzdbhzFN0OmFUt%2BIDCbAjGN9P2/Ew81AkdtisBl7lve9H0wZ8DFfd86UOeNE0uFlQPzd8zFDQ5MO%2BUdwLrG87wfJgn1OF82xQwdMIgXDQ0WQ4AFoP0w6E6NI6DYIoqi3Bot8PxMBIrDEtl8AUURiHQUSRwSId/wYMYvxSYhDiYWFUEOKgvHBepvmPTAIBYtkvw2FIOXY1CxnQEAQCxIw8QJQkuwIzACDWP87Icj41g2X5/korIHOQNZLkEUyADo9IMrIjJ3UziJzEcHj4%2BDoS0%2BdDm7ESxNEixJLwaTmjkxT5OU1TVHUzTtN0/SHAS4zTNZVALMwKy2I/XzHIIYhsRcol3MuLzfzQgh7Mcz5Ar%2BAFQpQCLGAIGK4qagRErYZLILHaD0I5BsWE2n4wn4a8HiTGZHGQKrbxqjTsp04y3iUtbDOM6EUwDdNM3FByOwc3t%2B1uOltqg%2B5Lqaa7brUh76tiYBlxOJTjNisJeXMMwvudH6szFf7XUBvsB0xlVIOBSGQputAVLu2rHs/Bh0BeiapoyAAvEzjMWViIFR7kMbMLH/RxjM8YJ2UieB0nrF6jmTLl/rBvxIlsMx7G0zFv6QABkAgZJoXwMWMnwdVVKeMeB59sONgKjiY7vlOnS1YuiaqZh%2B66vnZ7kYa%2BKNo%2B05OLzL8CE%2BkXNd%2BujoorKsaxI0GTYpt3oZp6r6fhzBEb/X2Poknc0aZiBMdj6tayFnmuHki3KdTgC6bh%2BdXBZ1GFC8aILj5guBeLoXS/jivZcmvy8E5iBFYG5yVeJMC%2B8rMvMaNpOUXN8mV7Sy3N4yyiEPeYfHNHn4ORlJHtiUjXAzdJVSFZkfOe%2BY%2BmFUFmL47eVPRvoSQfpCGPIARy8HgS4bZx77xKt8Q6eJoTf00kzcsT83iDhPgwb0jwCoSQwCVGS5UFJKTTg3L2OlIEtXwe2T8LM1apTMu1VQllrI9X3k5HE09zq/3wbDQhNsmAAGtXi%2B0KtXSk9UIg3Fai7X%2BSZSEMyoAwY6LMLxMDoA5N6zUdzQiungZA3xRBjGgaIkRlhkFk2wGDZOkj66cJ9mfXSsjW7t07gopRIBiE7kdgwfgDkEZhBvnLQ%2B1BbE7h5o42gDkXFsDcR45xTNWLBNCQwHwDsnaeKzmEZeEiPJjT/HYju/Uu5sELugX4LYCDfFQFQXuZgHIy0sFwNJSYE75iTE05pLTWktOTqNbyxwCp4UEW4R60VBmHAiAoURvV0Zfm%2BEoABjBDynBGYM6KNwWLYQyV03qVIaTYRYDwzA0Vt63kOKgFIcRKIkG2m4EZojFiLIabtdJoCpo7N4W4rAqgpmYBmeCXebgZRP1Ysg6wVc6SUKHCqMSGitE6LDqcLA%2BwCAIhORAP5qgAWpNEZgHmgKKpr0eKlNpBLCXtOgodMh2F7g3ysKvcGoc4h/mkagVAEBByYtYc0zp40wkmUxRbEiDwODLBCRwBIvA/AcC0KQVAnA3DWGsGhGafDQQ8FIAQTQArljcJAJISQ0VJBmASGYAAHDmbYCRQzbACIa6QQrJCirVZKzgvAFAgA0CqtVyw4CwBgIgFAqB7x0DiOQSgaB/X0HiM2IwXAcwaECDQWgP5nUQGiPa6IYRmgIk4Mq1NzBiAIgAPLRG0JgBwmbeAhrYIIPNDBaAZvFbwLA0QvDAH6bQWgzruD1rvIYdcmwJX4EuE1XEu57VfmLbCXtvAwi3iFcq%2BE0RqS5o8Fge1SsWCluWFQAwwAFDdlcnmk5YrlX8EECIMQ7ApAyEEIoFQ6g62kF0IEAwRgUCyssPoPAHd4DLGOfUdtrE7LI1MJYawZgNBsTzdsXgqAh3EAGlgZ1kBlh2GLfUFwTNJh%2BECCEDU8xhgFHSJkAQGG9CFEIwwOYQx4iBGQ%2BtBo4xWieHaHoGj9RegtAo3bKjth6PEeo/RjjCxakrACuewVnARWkDFRKqVHBDiqENaGVi4YmxPuAIcKN0UNDRS4IcZl%2BAiAaR2LU3gqq63G1IKuJgWB4imVIJqhIrqbW8DXdG6KOZJBJENQATg0DmIWhrQSSftTJp1Lq3VmdIJ6n1qwCApFhEGiAIaUgBuIBEHcnB5OKeU8AZAN0ID9X0twxYvBMD6ZIMWPQx7hCiHEBeqr161D2ofaQQk1IUjrv0OJu1d6ZN5thHFjkZS5MKaU5IFT3b1M5k09p3THhQ1xGOEq4r4WtDmcs9ZygYmOC2tIGuswXnor6u1VwDQXmzA5hzFGnMQWeuOtsGF0zq2NUjGigkdzl28KSG2KGHMhquChk6xwSDN3pN3ce%2BqwHZhuug44CZ91ywYMZGcJIIAA%3D%3D)
You declared reflect to work with clang so that's why i report

**Comment by krzysztof-jusiak** [comment]
it's a relatively new constexpr check in clang since clang-15:
clang-15 works https://godbolt.org/z/rPas4sT1z
it also works with with clang-17+ with -Wno-enum-constexpr-conversion - https://godbolt.org/z/n8Kcdzr6W. That can be done on the library side but I wanna avoid #pragma ignored in the code so looking for other options and don't wanna do it at run-time.
