### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by Nimrod0901** [boost-ext/reflect#46]
Hi! While delving into this repository, I happend to notice some subtle typos in README. I am wondering if contributions of fixing typos will be welcome? If so, I'd be glad to submit a PR with the necessary corrections.

**Comment by krzysztof-jusiak** [comment]
Hi @Nimrod0901. Thanks for looking at the library, and yeah, that would be more than welcome! Thank you!

**Comment by Nimrod0901** [comment]
I've submitted a [PR](https://github.com/boost-ext/reflect/pull/47) to fix the typos in the README. Please feel free to review it at your convenience, and don't hesitate to contact me if there are any adjustments needed or if you have any questions.
